apiVersion: v1
kind: Service
metadata:
  name: {{ include "civic-pulse.fullname" . }}-client
  labels:
    {{- include "civic-pulse.labels" . | nindent 4 }}
    component: client
spec:
  type: {{ .Values.client.service.type }}
  ports:
    - port: {{ .Values.client.service.port }}
      targetPort: {{ .Values.client.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "civic-pulse.selectorLabels" . | nindent 4 }}
    component: client
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "civic-pulse.fullname" . }}-server
  labels:
    {{- include "civic-pulse.labels" . | nindent 4 }}
    component: server
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "civic-pulse.selectorLabels" . | nindent 4 }}
    component: server
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "civic-pulse.fullname" . }}-mongodb
  labels:
    {{- include "civic-pulse.labels" . | nindent 4 }}
    component: mongodb
spec:
  type: {{ .Values.mongodb.service.type }}
  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: 27017
      protocol: TCP
      name: mongodb
  selector:
    {{- include "civic-pulse.selectorLabels" . | nindent 4 }}
    component: mongodb
