apiVersion: v2
name: civic-pulse
description: A Helm chart for deploying Civic-Pulse MERN application to Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - civic-pulse
  - mern
  - kubernetes
home: https://github.com/saheer/civic-pulse
sources:
  - https://github.com/saheer/civic-pulse
maintainers:
  - name: Saheer
    email: saheer@example.com
